-- SQL Server Data Check Script
-- Run this AFTER importing CSV data manually
-- Generated by export_sqlite_to_csv.py
-- Date: 2025-10-27 23:52:06.921922

-- ตั้งค่า Database
USE DrillingDatabase;
GO

-- ตรวจสอบจำนวนแถวในแต่ละตาราง
SELECT 'collars' as TableName, COUNT(*) as [RowCount] FROM collars
UNION ALL
SELECT 'lithology_logs' as TableName, COUNT(*) as [RowCount] FROM lithology_logs
UNION ALL
SELECT 'rock_types' as TableName, COUNT(*) as [RowCount] FROM rock_types
UNION ALL
SELECT 'seam_codes' as TableName, COUNT(*) as [RowCount] FROM seam_codes
UNION ALL
SELECT 'sample_analyses' as TableName, COUNT(*) as [RowCount] FROM sample_analyses;

-- ตรวจสอบข้อมูลตัวอย่างในแต่ละตาราง
PRINT '=== collars Sample Data ===';
SELECT TOP 5 * FROM collars;

PRINT '=== rock_types Sample Data ===';
SELECT TOP 5 * FROM rock_types;

PRINT '=== seam_codes Sample Data ===';
SELECT TOP 5 * FROM seam_codes;

PRINT '=== lithology_logs Sample Data ===';
SELECT TOP 5 * FROM lithology_logs;

PRINT '=== sample_analyses Sample Data ===';
SELECT TOP 5 * FROM sample_analyses;

-- ตรวจสอบ Foreign Key relationships
PRINT '=== Foreign Key Relationships ===';
SELECT 
    fk.name AS ForeignKeyName,
    tp.name AS ParentTable,
    cp.name AS ParentColumn,
    tr.name AS ReferencedTable,
    cr.name AS ReferencedColumn
FROM sys.foreign_keys fk
INNER JOIN sys.tables tp ON fk.parent_object_id = tp.object_id
INNER JOIN sys.tables tr ON fk.referenced_object_id = tr.object_id
INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
INNER JOIN sys.columns cp ON fkc.parent_object_id = cp.object_id AND fkc.parent_column_id = cp.column_id
INNER JOIN sys.columns cr ON fkc.referenced_object_id = cr.object_id AND fkc.referenced_column_id = cr.column_id
WHERE tp.name IN ('lithology_logs', 'sample_analyses')
ORDER BY tp.name, fk.name;

-- ตรวจสอบ Indexes
PRINT '=== Indexes ===';
SELECT 
    t.name AS TableName,
    i.name AS IndexName,
    i.type_desc AS IndexType,
    c.name AS ColumnName
FROM sys.tables t
INNER JOIN sys.indexes i ON t.object_id = i.object_id
INNER JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
WHERE t.name IN ('collars', 'lithology_logs', 'sample_analyses', 'rock_types', 'seam_codes')
ORDER BY t.name, i.name, ic.key_ordinal;
