-- SQL Server Table Creation Script (Ultra Safe Version)
-- For Manual CSV Import - Maximum safety for Import Wizard
-- Generated by export_sqlite_to_csv.py
-- Date: 2025-10-27 23:52:06.921922

-- ตั้งค่า Database
USE DrillingDatabase;
GO

-- ลบตารางเดิม (ถ้ามี)
IF OBJECT_ID('sample_analyses', 'U') IS NOT NULL DROP TABLE sample_analyses;
IF OBJECT_ID('lithology_logs', 'U') IS NOT NULL DROP TABLE lithology_logs;
IF OBJECT_ID('seam_codes', 'U') IS NOT NULL DROP TABLE seam_codes;
IF OBJECT_ID('rock_types', 'U') IS NOT NULL DROP TABLE rock_types;
IF OBJECT_ID('collars', 'U') IS NOT NULL DROP TABLE collars;
GO

-- สร้างตาราง (ขนาดคอลัมน์ปลอดภัยสูงสุด)
-- collars table
CREATE TABLE collars (
    hole_id NVARCHAR(50) PRIMARY KEY,
    easting FLOAT NOT NULL,
    northing FLOAT NOT NULL,
    elevation FLOAT,
    total_depth FLOAT,
    inclination FLOAT,
    year_drilled NVARCHAR(10),
    geologist NVARCHAR(50),
    block_no NVARCHAR(50),
    dh_version FLOAT,
    created_at DATETIME
);

-- rock_types table
CREATE TABLE rock_types (
    rock_id INT PRIMARY KEY,
    rock_code NVARCHAR(50) UNIQUE NOT NULL,
    rock_name NVARCHAR(100)
);

-- seam_codes table
CREATE TABLE seam_codes (
    seam_code_id INT PRIMARY KEY,
    seam_code NVARCHAR(50) UNIQUE NOT NULL,
    seam_label NVARCHAR(100),
    seam_system NVARCHAR(50)
);

-- lithology_logs table (ขนาดคอลัมน์ปลอดภัยสูงสุด)
CREATE TABLE lithology_logs (
    log_id INT PRIMARY KEY,
    hole_id NVARCHAR(50) NOT NULL,
    depth_from FLOAT NOT NULL,
    depth_to FLOAT NOT NULL,
    thickness FLOAT,
    rock_code NVARCHAR(50),
    description NVARCHAR(100),  -- ปลอดภัยสูงสุด
    clay_color NVARCHAR(100),   -- ปลอดภัยสูงสุด
    remark NVARCHAR(100)        -- ปลอดภัยสูงสุด
);

-- sample_analyses table
CREATE TABLE sample_analyses (
    sample_id INT PRIMARY KEY,
    hole_id NVARCHAR(50) NOT NULL,
    depth_from FLOAT,
    depth_to FLOAT,
    sample_no NVARCHAR(50) NOT NULL,
    im FLOAT,
    tm FLOAT,
    ash FLOAT,
    vm FLOAT,
    fc FLOAT,
    sulphur FLOAT,
    gross_cv FLOAT,
    net_cv FLOAT,
    sg FLOAT,
    rd FLOAT,
    hgi FLOAT,
    seam_code_quality INT,
    seam_code_73 INT,
    quality_seam_label NVARCHAR(100),
    seam_label_73 NVARCHAR(100)
);

-- สร้าง Indexes
CREATE INDEX idx_lithology_hole_id ON lithology_logs(hole_id);
CREATE INDEX idx_lithology_depth ON lithology_logs(depth_from, depth_to);
CREATE INDEX idx_samples_hole_id ON sample_analyses(hole_id);
CREATE INDEX idx_collars_depth ON collars(total_depth);
CREATE INDEX idx_rock_types_code ON rock_types(rock_code);
CREATE INDEX idx_seam_codes_code ON seam_codes(seam_code);

-- ตรวจสอบตารางที่สร้าง
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME IN ('collars', 'rock_types', 'seam_codes', 'lithology_logs', 'sample_analyses')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
